In [6]:
import pandas as pd

In [12]:
06_attendance = pd.read_csv("./2006.csv")

SyntaxError: invalid token (<ipython-input-12-0b5f99cfd08a>, line 1)

In [11]:
d2006

,Tm,Attendance,Attend/G,BatAge,PAge,BPF,PPF,#HOF,#A-S,#a-tA-S,Est. Payroll,Time,Managers
0,ARI,2091685,25823,29.7,28.8,105,105,0,1,14,$59984226,2:52,Melvin
1,ATL,2550524,31488,27.5,29.4,100,99,2,3,12,$90156876,2:50,Cox
2,BAL,2153139,26582,30.4,27.9,99,99,0,1,9,$72585582,2:53,Perlozzo
3,BOS,2930588,36180,30.5,31.1,105,104,0,4,18,$120099824,3:08,Francona
4,CHC,3123215,38558,28.6,28.0,103,103,1,1,13,$94424499,2:50,Baker
5,CHW,2957414,36511,29.8,27.9,104,104,1,7,16,$102750667,2:49,Guillen
6,CIN,2134607,26353,29.6,29.5,104,104,1,1,13,$60909519,2:50,Narron
7,CLE,1997995,24667,27.7,28.6,99,98,0,1,14,$56031500,2:54,Wedge
8,COL,2104362,25980,27.8,28.8,109,109,0,2,10,$41233000,2:51,Hurdle
9,DET,2595937,32049,29.3,28.8,100,99,1,3,15,$82612866,2:46,Leyland
10,FLA,1164134,14372,25.5,25.9,95,96,0,2,6,$14671500,2:51,Girardi
11,HOU,3022763,37318,30.5,29.8,100,99,1,2,9,$100894435,2:54,Garner
12,KCR,1372638,16946,29.7,27.7,101,103,0,1,9,$47694000,2:56,Bell
13,LAA,3406790,42059,28.8,27.9,100,99,1,1,15,$103472000,2:48,Scioscia
14,LAD,3758545,46402,29.9,30.4,101,100,1,2,23,$98447187,2:53,Little
15,MIL,2335643,28835,28.8,28.3,101,101,0,3,13,$57970333,2:52,Yost
16,MIN,2285018,28210,28.3,26.9,98,98,0,3,17,$63396006,2:46,Gardenhire
17,NYM,3379535,41723,30.2,32.2,98,97,2,6,15,$101584963,2:54,Randolph
18,NYY,4248067,52445,30.9,32.5,101,99,3,4,15,$194663079,3:08,Torre
19,OAK,1976625,24403,29.7,27.0,97,97,1,1,10,$64843079,2:47,Macha
20,PHI,2701815,33356,29.3,30.5,105,104,0,3,18,$88273333,2:56,Manuel
21,PIT,1861549,22982,27.8,27.0,98,99,0,2,13,$46717750,2:48,Tracy
22,SDP,2659757,32837,30.7,30.6,91,90,2,1,14,$69896141,2:50,Bochy
23,SEA,2481165,30632,28.7,28.0,97,97,0,2,16,$87959833,2:47,Hargrove
24,SFG,3130313,38646,33.7,28.7,100,100,0,1,14,$90056419,2:46,Alou
25,STL,3407104,42589,29.6,28.6,99,99,0,4,12,$88891371,2:51,La Russa
26,TBD,1368950,16901,27.3,27.0,99,100,0,1,7,$34917967,2:48,Maddon
27,TEX,2388757,29491,28.4,28.3,101,101,0,2,15,$68228662,2:49,Showalter
28,TOR,2302212,28422,28.6,28.1,100,100,1,5,11,$71365000,2:52,Gibbons
29,WSN,2153056,26581,28.5,28.9,94,95,0,1,10,$63143000,2:57,Robinson